"""Render and check the exhaustive TMS32010 opcode-space classification."""

from __future__ import annotations

import argparse
from pathlib import Path

from tools.generators.isa_database import (
    REPOSITORY_ROOT,
    audit_opcode_space,
    load_database,
)

DEFAULT_REPORT = (
    REPOSITORY_ROOT / "docs" / "generated" / "tms32010_opcode_audit.md"
)


def render_report(
    database: dict,
    counts: dict[str, int] | None = None,
) -> str:
    """Return the deterministic generated Markdown report."""
    actual = counts if counts is not None else audit_opcode_space(database)
    audit = database["opcode_space_audit"]
    lines = [
        "# TMS32010 opcode-space audit",
        "",
        "<!-- Generated by tools/generators/opcode_audit.py; do not edit. -->",
        "",
        f"**Status:** `{audit['status']}`",
        "",
        audit["claim_boundary"],
        "",
        "| Classification | Words | Meaning |",
        "|---|---:|---|",
    ]
    for definition in audit["classification_definitions"]:
        name = definition["name"]
        meaning = definition["meaning"].replace("|", "\\|")
        lines.append(f"| `{name}` | {actual[name]} | {meaning} |")
    lines.extend(
        [
            f"| **Total** | **{sum(actual.values())}** | Complete 16-bit partition. |",
            "",
            "The partition is exhaustive, but primary-unlisted does not mean reserved,",
            "illegal, inert, or trapped. Likewise, a pattern",
            "mismatch establishes only that the word is not the documented legal",
            "encoding. See `docs/architecture/opcode_map.md` for primary citations and",
            "the live qualification boundary.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_REPORT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed report differs instead of rewriting it",
    )
    args = parser.parse_args()
    database = load_database()
    counts = audit_opcode_space(database)
    report = render_report(database, counts)
    if args.check:
        try:
            committed = args.output.read_text(encoding="utf-8")
        except OSError as error:
            parser.error(f"cannot read {args.output}: {error}")
        if committed != report:
            parser.error(
                f"{args.output} is stale; regenerate with "
                "python3 -m tools.generators.opcode_audit"
            )
        print(f"PASS: opcode audit report ({sum(counts.values())} words)")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"WROTE: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
