`default_nettype none

// Synthesis-only harness for the sequential native-phase integration slice.
module tms32010_synth_top (
  input  logic        clk_i,
  input  logic        initialize_i,
  input  logic        rs_i,
  input  logic        clock_enable_i,
  input  logic [15:0] program_data_i,
  input  logic        debug_data_write_i,
  input  logic [7:0]  debug_data_address_i,
  input  logic [15:0] debug_data_i,

  output logic [11:0] pc_o,
  output logic [31:0] accumulator_o,
  output logic [15:0] t_register_o,
  output logic [31:0] product_register_o,
  output logic [15:0] auxiliary_register_0_o,
  output logic [15:0] auxiliary_register_1_o,
  output logic        auxiliary_register_pointer_o,
  output logic        data_page_pointer_o,
  output logic        overflow_flag_o,
  output logic        overflow_mode_o,
  output logic        interrupt_mask_o,
  output logic        instruction_valid_o,
  output logic        retired_o,
  output logic        illegal_o,
  output logic [31:0] cycle_count_o,

  output logic [1:0]  phase_o,
  output logic        clkout_o,
  output logic [11:0] native_address_o,
  output logic        men_n_o,
  output logic        sample_o,
  output logic        native_active_o,
  output logic [7:0]  data_address_o,
  output logic        data_read_o,
  output logic        data_write_o,
  output logic        data_address_valid_o,
  output logic [7:0]  data_write_address_o,
  output logic        data_write_address_valid_o,
  output logic [15:0] data_read_data_o,
  output logic [15:0] data_write_data_o
);
  tms32010_phase_slice phase_slice (
    .clk_i                         (clk_i),
    .initialize_i                  (initialize_i),
    .rs_i                          (rs_i),
    .clock_enable_i                (clock_enable_i),
    .program_data_i                (program_data_i),
    .debug_data_write_i            (debug_data_write_i),
    .debug_data_address_i          (debug_data_address_i),
    .debug_data_i                  (debug_data_i),
    .phase_o                       (phase_o),
    .clkout_o                      (clkout_o),
    .program_address_o             (native_address_o),
    .men_n_o                       (men_n_o),
    .sample_o                      (sample_o),
    .bus_active_o                  (native_active_o),
    .data_address_o                (data_address_o),
    .data_read_o                   (data_read_o),
    .data_write_o                  (data_write_o),
    .data_address_valid_o          (data_address_valid_o),
    .data_write_address_o          (data_write_address_o),
    .data_write_address_valid_o    (data_write_address_valid_o),
    .data_read_data_o              (data_read_data_o),
    .data_write_data_o             (data_write_data_o),
    .pc_o                          (pc_o),
    .accumulator_o                 (accumulator_o),
    .t_register_o                  (t_register_o),
    .product_register_o            (product_register_o),
    .auxiliary_register_0_o        (auxiliary_register_0_o),
    .auxiliary_register_1_o        (auxiliary_register_1_o),
    .auxiliary_register_pointer_o  (auxiliary_register_pointer_o),
    .data_page_pointer_o           (data_page_pointer_o),
    .overflow_flag_o               (overflow_flag_o),
    .overflow_mode_o               (overflow_mode_o),
    .interrupt_mask_o              (interrupt_mask_o),
    .instruction_valid_o           (instruction_valid_o),
    .retired_o                     (retired_o),
    .illegal_o                     (illegal_o),
    .cycle_count_o                 (cycle_count_o)
  );
endmodule

`default_nettype wire
